# Vector Matrix Calculations

## Question 1

After running the piece of code provided in the assignment interactively, we observe that initially when computing the dot product of two vectors a and b, the python-numpy returns the expected result for the inner product. However after transforming the vectors into column vectors, the dot product returns an error message. The error states that the dimensions of the operands are not valid, specifically "size 4 is different from 1". This implies that the dot product operator "@" does not inherantly know to use the transpose of one of the vectors to compute the outer product. This issue is resolved when using a.T as the operator. Furthermore, when attempting to print the float value of this computation, a deprication message is returned (as well as the correct answer), notifying the user that the functionality of converting all values in a matrix to a different data type using type-casting will be depricated in future versions of numpy

## Question 2

In [15]:
import numpy as np

In [ ]:
#first we assign the variables

t = np.array([-3, 2, 11])

a = np.array([-2, 6, 1])

# beginning of the calculations
t_cross_t = np.cross(t, t)

b = np.cross(t, a)

c = np.cross(a, t)

print(t_cross_t , b, c)

tb = np.dot(t, b)

ab = np.dot(a, b)

print(tb, ab)

[0 0 0] [-64 -19 -14] [64 19 14]
0 0


## Quesiton 3

In [17]:
t = np.array([-3, 2, 11])

def skew_symmetric_matrix(t):
    """
    This function returns the skew symmetric matrix of a vector t
    """
    return np.array([[ 0 , -t[2], t[1]],
                     [ t[2], 0, -t[0]],
                     [-t[1], t[0], 0]  ])

t_skew = skew_symmetric_matrix(t)

t_skew_dot_t = np.dot(t_skew, t)

t_skew_dot_a = np.dot(t_skew, a)

print("The skew matrix comprised of elements of vector t is:\n",t_skew)
print("The matrix vector product of the skew matrix and t is:\n",t_skew_dot_t)
print("The matrix vector product of the skew matrix and a is:\n",t_skew_dot_a)


The skew matrix comprised of elements of vector t is:
 [[  0 -11   2]
 [ 11   0   3]
 [ -2  -3   0]]
The matrix vector product of the skew matrix and t is:
 [0 0 0]
The matrix vector product of the skew matrix and a is:
 [-64 -19 -14]


Here we can see that the t^ association of the t vector returns a skew matrix comprised of the components of t.
t^ x t is a 3D null matrix, similar to t x t calculated in the previous question
t^ x a is equivalent to t x a calculated in the previous question

## Question 4

t x v can also be represented by the dot product t^v

## Question 5

In [18]:
t_skew = skew_symmetric_matrix(t)
t_skew_transpose = np.transpose(t_skew)


if(t_skew_transpose == -1*t_skew).all():
    print("The skew matrix is skew symmetric")

The skew matrix is skew symmetric


In [19]:
t_skew_squared = np.dot(t_skew, t_skew)

t_skew_squared_transpose = np.transpose(t_skew_squared)

t_skew_cubed_transpose = np.transpose(np.dot(t_skew, t_skew_squared))

print("The transpose of the square of the skew matrix is:\n",t_skew_squared_transpose)
print("The transpose of the cube of the skew matrix is:\n",t_skew_cubed_transpose)

The transpose of the square of the skew matrix is:
 [[-125   -6  -33]
 [  -6 -130   22]
 [ -33   22  -13]]
The transpose of the cube of the skew matrix is:
 [[    0 -1474   268]
 [ 1474     0   402]
 [ -268  -402     0]]
